name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "packages/shared/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - name: Install dependenccies
        run: npm ci
      - name: Build shared packages
        run: npm run build -w packages/shared
      - name: Build Backend
        run: npm run build -w backend
      - name: Production package files
        run: |
          mkdir -p deploy-package/backend
          cp -r backend/dist deploy-package/backend/dist
          cp backend/package.json deploy-package/backend/package.json
          cp backend/package-lock.json deploy-package/backend/package-lock.json
          cp -r packages/shared/dist deploy-package/packages/shared/dist
      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: "deploy-package/"
          target: "~/app-incoming"
          strip_components: 1
      - name: Deploy and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Installing production dependencies..."
            cd ~/app-incoming/backend
            npm ci --omit=dev

            echo "Adding files to backend"
            rm -rf ~/app/backend/dist ~/app/backend/node_modules
            cp -r ~/app-incoming/backend/dist ~/app/backend/dist 
            cp -r ~/app-incoming/backend/node_modules ~/app/backend/node_modules

            echo "Restarting PM2..."
            if pm2 list | grep -q resqplate-backend; then
                pm2 restart resqplate-backend
            else
                cd ~/app/backend && pm2 start dist/server.js --name resqplate-backend
                pm2 startup | tail -1 | sudo bash
                pm2 save
            fi

            echo "Verifying PM2 backend..."
            sleep 2
            pm2 list | grep resqplate-backend
